### ISSUE TITLE
랭크 게임이 아닐 경우에 게임 결과 전송 요청 시 오류 발생

### ISSUE THREAD

**Issue by HyeonJung** [HyeonJung/lolhuni#2]
## 오류 발생

- 일반 게임, 사용자 정의 게임에서 발생
- 자유랭, 포로왕 등 다른 것도 확인 필요

## 로그

```
 115 java.lang.NullPointerException: null
  116         at com.hj.lolhuni.service.GameServiceImpl.getGameResult(GameServiceImpl.java:176)
  117         at com.hj.lolhuni.service.GameServiceImpl.sendGameResult(GameServiceImpl.java:122)
  118         at com.hj.lolhuni.schedule.ScheduledTasks.checkCurrentGame(ScheduledTasks.java:82)
  119         at sun.reflect.GeneratedMethodAccessor138.invoke(Unknown Source)
  120         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  121         at java.lang.reflect.Method.invoke(Method.java:498)
  122         at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
  123         at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
  124         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  125         at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
  126         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
  127         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
111
  128         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  129         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  130         at java.lang.Thread.run(Thread.java:748)
```

**Comment by HyeonJung** [comment]
랭크게임이 아닌경우에는 player의 상세 정보를 내려주지 않아서 null 값으로 나옴.
일반게임일 경우에는 kda를 안 보여주도록 수정
